In [99]:
import pandas as pd
import numpy as np
import sklearn as sk
import matplotlib.pyplot as plt

#Classification with KNN
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [95]:
# Lade DataFrame Walk
df_walk_Acc= pd.read_csv('data/NormalWalk/Accelerometer.csv')
df_walk_Gyr= pd.read_csv('data/NormalWalk/Gyroscope.csv')
df_walk_Ori= pd.read_csv('data/NormalWalk/Orientation.csv')

# Lade DataFrame PushUps
df_push_Acc= pd.read_csv('data/PushUps/Accelerometer.csv')
df_push_Gyr= pd.read_csv('data/PushUps/Gyroscope.csv')
df_push_Ori= pd.read_csv('data/PushUps/Orientation.csv')

# Lade DataFrame JumpingJacks
df_JJ_Acc= pd.read_csv('data/JJ_rightHand/Accelerometer.csv')
df_JJ_Gyr= pd.read_csv('data/JJ_rightHand/Gyroscope.csv')
df_JJ_Ori= pd.read_csv('data/JJ_rightHand/Orientation.csv')

In [96]:
df_push_Gyr.head(10)

time  seconds_elapsed         z         y         x
0  1682879936119105000         0.143105 -0.804662 -0.890642 -0.137750
1  1682879936136056300         0.160056 -0.647517 -1.406670 -1.012204
2  1682879936152943000         0.176943 -0.459218 -1.498758 -1.637577
3  1682879936169797600         0.193798 -0.178220 -1.946369 -2.109318
4  1682879936186679000         0.210679  0.304211 -2.204154 -2.401006
5  1682879936203543800         0.227544  0.877813 -2.459954 -2.292883
6  1682879936220417800         0.244418  1.293507 -2.755766 -1.811826
7  1682879936237296400         0.261296  1.358106 -2.126117 -1.204932
8  1682879936254168300         0.278168  0.932486 -1.213178 -0.844216
9  1682879936271039000         0.295039  0.284358 -0.092852 -0.382402

In [97]:
#Concat DataFrames Walk
df_walk_Gyr.drop(['time','seconds_elapsed'], axis=1, inplace=True)
df_walk_Ori.drop(['time','seconds_elapsed'], axis=1, inplace=True)
df_walk = pd.concat([df_walk_Acc, df_walk_Gyr, df_walk_Ori], axis=1)

#Concat DataFrames PushUps
df_push_Gyr.drop(['time','seconds_elapsed'], axis=1, inplace=True)
df_push_Ori.drop(['time','seconds_elapsed'], axis=1, inplace=True)
df_push = pd.concat([df_push_Acc, df_push_Gyr, df_push_Ori], axis=1)
df_push.head(10)

#Concat DataFrames JumpingJacks
df_JJ_Gyr.drop(['time','seconds_elapsed'], axis=1, inplace=True)
df_JJ_Ori.drop(['time','seconds_elapsed'], axis=1, inplace=True)
df_JJ = pd.concat([df_JJ_Acc, df_JJ_Gyr, df_JJ_Ori], axis=1)
df_JJ.head(10)

time  seconds_elapsed         z         y         x  \
0  1682879829644700400         0.197700  0.247896 -0.302020  1.391320   
1  1682879829661591300         0.214591 -0.839892  0.808964  0.504949   
2  1682879829678456800         0.231457 -1.454709  2.047860 -1.821745   
3  1682879829695329000         0.248329 -1.158190  1.843092 -1.915896   
4  1682879829712205300         0.265205 -1.149807  0.030297 -0.715421   
5  1682879829729065700         0.282066 -1.454511 -0.696599 -0.916581   
6  1682879829745946400         0.298946 -1.563555 -3.306457  0.347007   
7  1682879829762819800         0.315820 -1.407818 -3.109730  1.307576   
8  1682879829779689700         0.332690 -0.325881 -0.319399  1.145536   
9  1682879829796561200         0.349561 -0.275145  0.455923  0.994993   

          z         y         x        qz        qy        qx        qw  \
0  0.588874 -0.096211 -0.076205  0.614930  0.096542  0.204705  0.755405   
1  0.552833 -0.135459  0.250455  0.613941  0.105724  0.207268  0.754280   
2  0.450819  0.095600  0.561843  0.608168  0.111593  0.210562  0.757194   
3  0.296575  0.509767  0.784046  0.598106  0.113505  0.212696  0.764295   
4 -0.057421  0.680962  0.926072  0.587303  0.115688  0.214443  0.771820   
5 -0.635453  0.287107  0.836885  0.577234  0.118879  0.218358  0.777810   
6 -1.312444 -0.261908  0.365145  0.569927  0.120131  0.227486  0.780386   
7 -1.558012 -0.344070  0.242208  0.566548  0.120605  0.239539  0.779165   
8 -1.437060 -0.234114  0.443183  0.564275  0.123492  0.251334  0.776643   
9 -0.984868 -0.649655  0.881784  0.562355  0.128571  0.259650  0.774473   

       roll     pitch       yaw  
0 -0.117447 -0.442283 -1.392921  
1 -0.106146 -0.458376 -1.391155  
2 -0.097966 -0.471931 -1.376934  
3 -0.091317 -0.479010 -1.350345  
4 -0.082991 -0.485794 -1.321499  
5 -0.076481 -0.497152 -1.296308  
6 -0.082571 -0.514369 -1.283294  
7 -0.097197 -0.535114 -1.284059  
8 -0.108478 -0.558318 -1.287777  
9 -0.111163 -0.578523 -1.289188

In [ ]:
df_walk_Gyr.plot(x='time', y='z', kind='line')
df_walk_Gyr.plot(x='time', y='y', kind='line')
df_walk_Gyr.plot(x='time', y='x', kind='line')

In [ ]:
#Plotting Gyroscope Data
#Function to plot Gyr Data
def plotDataGyr(data, title):
    plt.plot(data['time'], data['z'], color='red', marker='.')
    plt.plot(data['time'], data['y'], color='blue', marker='.')
    plt.plot(data['time'], data['x'], color='green', marker='.')
    plt.xlabel('time')
    plt.ylabel('x,y,z')
    plt.legend(['z', 'y', 'x'])
    plt.title(title)
    plt.show()

#Plot Walk
plotDataGyr(df_walk_Gyr, 'Gyroscope Walk')

#Plot PushUps
plotDataGyr(df_push_Gyr, 'Gyroscope PushUps')

#Plot JumpingJacks
plotDataGyr(df_JJ_Gyr, 'Gyroscope JumpingJacks')


In [ ]:
#Plotting Accelerometer Data
#Function to Plot Acc Data
def plotDataAcc(data, title):
    plt.plot(data['time'], data['z'], color='red', marker='.')
    plt.plot(data['time'], data['y'], color='blue', marker='.')
    plt.plot(data['time'], data['x'], color='green', marker='.')
    plt.xlabel('time')
    plt.ylabel('x,y,z')
    plt.legend(['z', 'y', 'x'])
    plt.title(title)
    plt.show()

#Plot Walk
plotDataAcc(df_walk_Acc, 'Accelerometer Walk')

#Plot PushUps
plotDataAcc(df_push_Acc, 'Accelerometer PushUps')

#Plot JumpingJacks
plotDataAcc(df_JJ_Acc, 'Accelerometer JumpingJacks')

In [ ]:
#Plotting Orientation Data
#Function to Plot Ori Data
def plotDataOri(data, title):
    plt.plot(data['time'], data['qz'], color='red', marker='.')
    plt.plot(data['time'], data['qy'], color='blue', marker='.')
    plt.plot(data['time'], data['qx'], color='green', marker='.')
    plt.plot(data['time'], data['qw'], color='yellow', marker='.')
    #plt.plot(data['time'], data['roll'], color='black', marker='.')
    plt.xlabel('time')
    plt.ylabel('qz,qy,qx,qw,roll')
    plt.legend(['qz', 'qy', 'qx', 'qw', 'roll'])
    plt.title(title)
    plt.show()

#Plot Walk
plotDataOri(df_walk_Ori, 'Orientation Walk')

#Plot PushUps
plotDataOri(df_push_Ori, 'Orientation PushUps')

#Plot JumpingJacks
plotDataOri(df_JJ_Ori, 'Orientation JumpingJacks')
    

In [111]:
#Classification with KNN
#Function to label the data
def getData(data, label):
    data['label'] = label
    return data

#Label Data Walk
df_walk = getData(df_walk, 'walk')
df_walk.head(10)

#Label Data PushUps
df_push = getData(df_push, 'pushups')
df_push.head(10)

#Label Data JumpingJacks
df_JJ = getData(df_JJ, 'jumpingjacks')
df_JJ.head(10)

#Concat DataFrames
df = pd.concat([df_walk, df_push, df_JJ], axis=0)

#Fill NaN Values with 0
df.fillna(0, inplace=True)

#Split Data
X = df.drop(['label'], axis=1)
y = df['label']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

#KNN
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)

#Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

#Accuracy
accuracy = accuracy_score(y_test, y_pred)
print(accuracy)


[[384   0   0]
 [  0 612   0]
 [  0   0 521]]
1.0
